In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a.shape # taille

(3,)

In [4]:
a.ndim # nombre de dimension

1

In [6]:
B = np.zeros((3,3)) #initialise un tableau 2d remplis de 0
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.random.randn(3,4) 
#génère des nombres aléatoires dans un tableau

array([[ 0.55480357,  0.48749278, -2.59525446, -0.83510673],
       [ 0.30078768,  0.89748774, -0.06017212,  1.2666685 ],
       [ 0.62620088,  0.01076669,  0.95292645,  0.17923272]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.linspace(0,10,20, dtype=np.float16) 
#répartie un tableau de 0 à 10 sur 20 points
#dtype défini le type de données

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
np.arange(0, 10, 1) #crée un tableau de 0 à 10 avec un pas de 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# MANIPULATION

In [16]:
A = np.ones((2,2))
B = np.zeros((2,2))
np.hstack((A, B)) # colle les deux tableaux horizontalement

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [17]:
np.vstack((A, B)) # colle les deux tableau verticalement

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [ ]:
D = np.concatenate((A, B), axis=1)
# fait la même chose que vstack et hstack

In [23]:
D.size

8

In [25]:
D.reshape((2,4)) # change les dimension du tableau que si size = 8

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [27]:
E = np.array([1,2,3])
E = E.reshape((E.shape[0], 1)) # ajoute une dimension au shape
E.shape

(3, 1)

In [31]:
E = E.squeeze() # supprime une dimension au shape
E.shape

(3,)

In [32]:
D.ravel() # affiche un tableau sur une seul dimension

array([1., 1., 0., 0., 1., 1., 0., 0.])

# EXO

In [43]:
def initialisation(m, n):
    A = np.random.randn(m, n)
    #B = np.ones((m, n - (n -1)))
    #C = np.concatenate((A, B), axis=1)
    A = np.concatenate((A, np.ones((A.shape[0], 1))), axis=1)
    return A

In [44]:
initialisation(2,2)

array([[-0.19079847, -1.46247064,  1.        ],
       [-1.29449203, -0.13221027,  1.        ]])